### ISSUE TITLE
Rofi

### ISSUE THREAD

**Issue by drmarwat** [Michael-F-Bryan/dotfiles#2]
Thanks for sharing your dots , everything works like a breeze out of box . Would you like to add rofi to your dots setup as well please so it comes installed and set up out of box as everything else?

**Comment by Michael-F-Bryan** [comment]
Can you make a PR with the required changes?

Alternatively, you can always fork this repository and make whatever changes you want.to customise it to your system.

**Comment by drmarwat** [comment]
Sure I will send you such requests on your email next time ( same email
given in your install.py script secrets section? )

**Comment by Michael-F-Bryan** [comment]
I don't use Rofi so it might actually be better for you to add it to your own fork instead of trying to merge it into my dotfiles.
